config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'new_name', to: 'devise/registrations#new_name', as: 'new_name'
    patch 'create_name', to: 'devise/registrations#create_name', as: 'create_name'
  end
  get 'users/:id' => 'users#show'
  root 'boards#index'
  resources :boards
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards, dependent: :destroy

  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :correct_user, only: %i[edit destroy]

  def index
    @boards = Board.includes(:user)
  end

  def new
    @board = Board.new
  end

  def create
    board = current_user.boards.create!(board_params)
    redirect_to boards_path
  end

  def show
    @board = Board.find(params[:id])
  end

  def edit
  end

  def update
    board = Board.find(params[:id])
    board.update(board_params)
    redirect_to boards_path
  end

  def destroy
    Board.destroy(params[:id])
    redirect_to boards_path
  end

  private

  def board_params
     params.require(:board).permit(:name, :title, :body, :url)
  end

  def correct_user
    @board = current_user.boards.find_by(id: params[:id])
    redirect_to boards_path if @board.nil?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # # callback for facebook
  # def facebook
  #   callback_for(:facebook)
  # end

  # # callback for twitter
  # def twitter
  #   callback_for(:twitter)
  # end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      @user.save
      sign_in @user
      redirect_to new_name_path
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @boards = Board.where(user_id: current_user.id).all
    @board = Board.where(user_id: current_user.id)
  end

  def crea
    # 記事作成
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper

  def youtube_link
    p (@board.url).last(11)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(board.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
    <% if youtube_link.present? %>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= youtube_link %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %>
  </div>
</div>

app/views/boards/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_for @board do |f| %>
      <div class ="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class ="form-group">
        <%= f.label :body, '本文' %>
        <%= f.text_area :body, class: 'form-control', rows: 10 %>
      </div>
      <div class ="form-group">
        <%= f.label :url, 'YouTubeリンク' %>
        <%= f.text_field :url, class: 'form-control' %>
      </div>
      <%= f.submit '保存', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>一覧</h1>
  <%# 画面を実装したことにします %>
  <div class="ml-auto boards_linkBox">
    <%= link_to '新規作成', new_board_path, remote: true, class: 'btn btn-outline-dark' %>
  </div>
</div>
<table class="table table-hover boards_table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= board.created_at.to_s(:datetime_jp) %></td>
        <td><%= board.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to '詳細', board, class: 'btn btn-outline-dark' %></td>
        <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="board-modal" class="modal" tabindex="-1" role="dialog"></div>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/new.js.erb
$('#board-modal').html('<%= j render('boards/form') %>')
$('#board-modal').modal('show')

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    <%= link_to '編集', edit_board_path(@board), class: 'btn btn-outline-dark' %>
  </div>
</div>

<%= render @board %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <a class="navbar-brand" href="#">Language Bank</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to '管理者', new_admin_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to '一覧', boards_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <a href="/users/<%= current_user.id %>" class="nav-link">マイページ</a>
          </li>
          <li class="nav-item active">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Language Bank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/show.html.erb
<div class="d-flex align-items-center">
  <h1>マイページ</h1>
  <div class="ml-auto boards_linkBox">
    <%= link_to '新規作成', new_board_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<table class="table table-hover boards_table">
  <thead class="thead-dark">
    <tr>
      <th>タイトル</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.title %></td>
        <td><%= board.created_at.to_s(:datetime_jp) %></td>
        <td><%= board.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to '詳細', board, class: 'btn btn-outline-dark' %></td>
        <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>